apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
  name: gold-fare-O6PCG2Y
spec:
  forProvider:
    kubernetesVersion: '1.25'
    defaultNodePool:
    - name: default
      nodeCount: '1'
      vmSize: Standard_D2_v2
    dnsPrefix: pref-gold-fare-O6PCG2Y
    identity:
    - type: SystemAssigned
    location: West Europe
    resourceGroupName: CloudNative-InfraMgmt-CTIO
  publishConnectionDetailsTo:
    name: kubeconfig-gold-fare-O6PCG2Y
  writeConnectionSecretToRef:
    name: kubeconfig-gold-fare-O6PCG2Y
    namespace: managed-resources
