apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
  name: roaring-channel-C0NV08B
spec:
  forProvider:
    kubernetesVersion: '1.25'
    defaultNodePool:
    - name: default
      nodeCount: '2'
      vmSize: Standard_D2_v2
    dnsPrefix: pref-roaring-channel-C0NV08B
    identity:
    - type: SystemAssigned
    location: West Europe
    resourceGroupName: CloudNative-InfraMgmt-CTIO
  publishConnectionDetailsTo:
    name: kubeconfig-roaring-channel-C0NV08B
  writeConnectionSecretToRef:
    name: kubeconfig-roaring-channel-C0NV08B
    namespace: managed-resources
