apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
  name: fixed-gator-UL2DAA8
spec:
  forProvider:
    kubernetesVersion: '1.25'
    defaultNodePool:
    - name: default
      nodeCount: '2'
      vmSize: Standard_D2_v2
    dnsPrefix: pref-fixed-gator-UL2DAA8
    identity:
    - type: SystemAssigned
    location: West Europe
    resourceGroupName: CloudNative-InfraMgmt-CTIO
  publishConnectionDetailsTo:
    name: kubeconfig-fixed-gator-UL2DAA8
  writeConnectionSecretToRef:
    name: kubeconfig-fixed-gator-UL2DAA8
    namespace: managed-resources
