apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
  # annotations:
  #   meta.upbound.io/example-id: containerservice/v1beta1/kubernetescluster
  # labels:
  #   testing.upbound.io/example-name: example
  # name: myakscluster01
  name: clustername
spec:
  forProvider:
    # Force K8s version
    kubernetesVersion: 1.26
    defaultNodePool:
    - name: default
      nodeCount: 1
      # nodeCount: node_count
      vmSize: Standard_D2_v2
      # vmSize: vmSize
    # dnsPrefix: pref-myakscluster01
    dnsPrefix: pref-clustername
    identity:
    - type: SystemAssigned
    location: "West Europe"
    # resourceGroupName: CloudNative-InfraMgmt-CTIO
    resourceGroupName: resourcegroup
    # # In case we had created the RG with CrossPlane:
    # resourceGroupNameSelector:
    #   matchLabels:
    #     testing.upbound.io/example-name: example
    # tags:
    #   Environment: Production
  # # Use in case you wanted to use different credentials (i.e., ProviderConfig different than default)
  # providerConfigRef: default
  publishConnectionDetailsTo:
    # name: kubeconfig-myakscluster01
    name: kubeconfig-clustername
  writeConnectionSecretToRef:
    # name: kubeconfig-myakscluster01
    name: kubeconfig-clustername
    # namespace: crossplane-system
    namespace: managed-resources
