apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: generate-and-print-message-template
spec:
  serviceAccountName: argo
  entrypoint: generate-and-print-message
  templates:
    - name: generate-and-print-message
      steps:
      - - name: generate-message
          template: generate-message
      - - name: print-message
          template: print-message
          arguments:
            parameters:
            - name: message
              value: "{{steps.generate-message.outputs.parameters.message}}"

    # Templates
    - name: generate-message
      serviceAccountName: argo
      container:
        image: docker/whalesay:latest
        command: [sh, -c]
        args: ["echo -n hello world > /tmp/message.txt"]
      outputs:
        parameters:
        - name: message  # name of output parameter
          valueFrom:
            path: /tmp/message.txt # set the value of message to the contents of message.txt

    - name: print-message
      serviceAccountName: argo
      inputs:
        parameters:
        - name: message
      container:
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
